### ISSUE TITLE
Can't resize address bar

### ISSUE THREAD

**Issue by LulaSvob** [hakan-demirli/Firefox_Custom_CSS#1]
Hello,

Very nice theme and thanks for sharing it with the community. 
One thing I am trying to achieve is to resize the address bar. 
Do you have any idea how to achieve it in this setup? At the moment it's really narrow (as it appears in your images) and I'd like it to take up more space in the middle of the window

**Comment by hakan-demirli** [comment]
6th line of the userChrome.css defines the starting point of the navigation bar contents.
`  --uc-window-control-width: 898px; /* Space reserved for window controls */`

Decreasing it will cause extension icons to shift right. The address bar will expand automatically.
![Screenshot (27)](https://user-images.githubusercontent.com/78746991/129494008-5409b74d-f113-4893-a062-154ee20b4284.png)

Pad the address bar to shift it. It can be centered this way.
![Screenshot (29)](https://user-images.githubusercontent.com/78746991/129494031-d0e050a0-dc57-46c1-b2dc-3b15550b99bd.png)

Here is a mirrored look:
![Screenshot (31)](https://user-images.githubusercontent.com/78746991/129494088-e9c28ea5-bcfa-4767-9f4c-e4568cb6fe56.png)

Or big chungus:
![Screenshot (32)](https://user-images.githubusercontent.com/78746991/129494201-aba81acf-5db5-49cf-98d6-3631e29766b7.png)

**Comment by LulaSvob** [comment]
Incredible. Thanks a ton. I tried increasing this space but didn't think that I need to decrease it. It worked just fine.
