### ISSUE TITLE
Add Tabs to the right side of (empty space) panel

### ISSUE THREAD

**Issue by aspirus-in** [hakan-demirli/Firefox_Custom_CSS#2]

**Comment by hakan-demirli** [comment]
I assume by the empty space you mean the right side of the menu button:
![overall](https://user-images.githubusercontent.com/78746991/134916375-6ab9e812-b03d-4753-8d8b-b87421d24662.png)   
If so, delete the /*Disable_Horizontal_Tabs */ section (line 3 to 105) of the user_Chrome.css file and paste the following code block to the section.
```
:root:-moz-any([inFullscreen], [tabsintitlebar]) #TabsToolbar:not(:-moz-lwtheme) { -moz-appearance: none !important; }
#TabsToolbar {
  background-color: #000000 !important;
  margin-bottom: 0px !important;
  margin-top: 0px !important;
  margin-left: 35vw !important;
  margin-right: 0px !important;
  max-height: 35px !important;
  height: 35px !important
}

#nav-bar {
  margin-bottom: 0px !important;
  margin-top: -35px !important;
  margin-left: 0px !important;
  margin-right: 65vw !important;
  border-top: none !important;
  height: 35px;
  background-color: black !important;
}
```
This is the final result:
![Screenshot (55)](https://user-images.githubusercontent.com/78746991/134916108-56af69b1-591a-43b9-86a4-14dd1246b591.png)

Try to edit the pixel values to fit your liking.

**Comment by hakan-demirli** [comment]
Since it has been two days, I will close the issue for now. But if the solution doesn't work, feel free to open it again.
